# Generated by Django 3.1.2 on 2021-07-26 04:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('mobileno', models.CharField(blank=True, max_length=10, null=True)),
                ('complaint', models.CharField(blank=True, max_length=100, null=True)),
                ('modelname', models.CharField(blank=True, max_length=100, null=True)),
                ('modelbrand', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('images', models.ImageField(null=True, upload_to='', verbose_name='images')),
            ],
        ),
        migrations.CreateModel(
            name='Customerdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('mobileno', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Devicedetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelbrand', models.CharField(blank=True, max_length=100, null=True)),
                ('modelname', models.CharField(blank=True, max_length=100, null=True)),
                ('modelno', models.CharField(blank=True, max_length=100, null=True)),
                ('imeino', models.CharField(blank=True, max_length=16, null=True)),
                ('colour', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('mobileno', models.CharField(blank=True, max_length=10)),
                ('complaint', models.CharField(blank=True, max_length=100, null=True)),
                ('modelname', models.CharField(blank=True, max_length=100, null=True)),
                ('modelbrand', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('images', models.ImageField(null=True, upload_to='', verbose_name='images')),
                ('status', models.CharField(choices=[('completed', 'completed'), ('deliverd', 'deliverd'), ('recived', 'recived'), ('working', 'working')], default='working', max_length=20)),
                ('payment', models.IntegerField(null=True)),
                ('expected_delivery', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cust.customer')),
            ],
            options={
                'ordering': ['-created', 'uuid'],
            },
        ),
    ]
